### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by joemphilips** [joemphilips/walletts#3]
* [x] configure CI
  * [x] run tests on circleci
  * [x] publish from circle ci
* [x] semantic release
* [x] define HOC to provide theme and i18n to components

**Comment by joemphilips** [comment]
I decided these are better moved to the project page
